language: scala

git:
  depth: false # Avoid sbt-dynver not seeing the tag
  
env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

scala:
  - 2.12.13
  - 2.13.5

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

script:
  - sbt ++$TRAVIS_SCALA_VERSION 'testOnly -- xonly timefactor 5' mimaReportBinaryIssues validateCode doc
  # Check that we can actually build and package the library
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal


jobs:
  include:
    - stage: test
      name: "Validations"
      script: sbt mimaReportBinaryIssues validateCode doc
      env:
        - TRAVIS_SCALA_VERSION=2.13.5
        - TRAVIS_JDK=11

    - name: "Run tests with Scala 2.12 and AdoptOpenJDK 11"
      env:
        - TRAVIS_SCALA_VERSION=2.12.13
        - TRAVIS_JDK=11

    - name: "Run tests with Scala 2.13 and AdoptOpenJDK 11"
      env:
        - TRAVIS_SCALA_VERSION=2.13.5
        - TRAVIS_JDK=11

    - name: "Run tests with Scala 2.12 and AdoptOpenJDK 8"
      env:
        - TRAVIS_SCALA_VERSION=2.12.13
        - TRAVIS_JDK=8

    - name: "Run tests with Scala 2.13 and AdoptOpenJDK 8"
      env:
        - TRAVIS_SCALA_VERSION=2.13.5
        - TRAVIS_JDK=8

    - stage: publish
      name: "Publish artifacts to Sonatype"
      script: sbt +publish

stages:
  - name: test
  - name: publish
    if: (tag IS present) AND NOT fork

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.jabba/jdk"

before_cache:
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  slack:
    secure: gEa3XQiBUbMxCy+zzwka1cRcoc/h+lcOYFWiDM7JVxrPJxqAZcrlzSHqMrCEiey39bolMDWdRM9RhrJ/jkjOurHgDWN/oyhV4JRvXQJmipLDErRwuWemo1S15DcVeZ4+3VCmB3KIMKk0AWPjPZb2QEIQfzjNwd9MRXZPyWw9XiNjjUCC4VEjYxYlxIYhha4NaFRy96nTm/Rf6hc55bZeFYYz6Y42pK6sRN+M8ES9KsoW2KQeoxIXHp1bq3WxVPGlUPyhUroh53kehS6iS3tChMVw8fnFUbd8cvtNx/dN847Pwj1E2hLhdD+aTjf8Wjq6V+l+RNWJnWdKIo+4bi0vqLZkUN7XrS9FgwX1cawdC32tNFlKXA4fmvXxtyMh3bGE011NVGtcdE2MBudy6lfYSvxROeDXwd+0xTbvyYd8xQrZv3JL3dTM3Hb+586NeZOTq2BpZJytKh4wIZcHyOeHdq+IbvPviERaem/d/wJ1QLVHspQw7xab8JopMWJ5iyJnCL9nC35hZomvzSyZ8KrVQKyMenbq7Kb8Vp/Lo5kCp1ygK8qfSNVl+sZfoW5D1dlipXDp2EYP399hqGa1kn23cIT1JiAbeQ9SEmhXWj4lPAq2rTAOt90V6OcpTqydJ3k/TVqzraZ3pGDirkrfS4kAvhgeIWIGDUnYXak5tpCoIcY=
