name: Check

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Code Style
    uses: playframework/.github/.github/workflows/cmd.yml@dynamic_matrix
    with:
      cmd: sbt validateCode

  check-binary-compatibility:
    name: Binary Compatibility
    uses: playframework/.github/.github/workflows/binary-check.yml@v1

  check-docs:
    name: Docs
    uses: playframework/.github/.github/workflows/cmd.yml@dynamic_matrix
    with:
      cmd: sbt doc

  tests:
    name: Tests
    needs: # Waiting more lightweight checks
      - "check-code-style"
      - "check-binary-compatibility"
      - "check-docs"
    uses: playframework/.github/.github/workflows/cmd.yml@dynamic_matrix
    with:
      java: >-
        [ "11", "8" ]
      add-dimensions: >-
        {
          "scala": [ "2.13.8", "3.1.2-RC3" ]
        }
      cmd: sbt ++$MATRIX_SCALA 'testOnly -- xonly timefactor 5'

  finish:
    name: Finish
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v1
